bind = "unix:{{django.socketfile}}"
workers = 2
max_requests = 100
max_request_jitter = 10
preload = True
#loglevel = 'INFO'
#accesslog = '{{ django.logto }}/gunicorn_access.log'
#errorlog = '{{ django.logto }}/gunicorn_error.log'
accesslog = '{{ django.logto }}/gunicorn.log'
errorlog = '{{ django.logto }}/gunicorn.log'
timeout = 300
