# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='value',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
