# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20171229_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='raw',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
